#!/bin/bash

SSHLS_PATH="$DOTFILES/sshls/connections"

main() {
        selectConnection;
}

initVars(){
        SSHLS_OPTIONS=$(cat $SSHLS_PATH |  awk '{print v++,$1}');
        SSHLS_CONNECTIONS=$(cat $SSHLS_PATH |  awk -F '[:]' '{print $2}');
        SSHLS_USER=$(cat $SSHLS_PATH |  awk -F '[:]' '{print $3}');
}

sendDialog(){
        echo $1 $2;
        exec 3>&1;
        result=$(dialog --menu $1 15 50 7 {$2[@]} 2>&1 1>&3);
        exitcode=$?;
        exec 3>&-;
        echo $result $exitcode;
    return result;
}

selectConnection() {

        initVars;

        exec 3>&1;
        result=$(dialog --menu "Select Host" 15 70 7 $SSHLS_OPTIONS 2>&1 1>&3);
        exitcode=$?;
        exec 3>&-;
        echo "RESULT" $result "EXITCODE" $exitcode;

        if [ $exitcode != "0" ]; then
                exit;
        fi

        if [ $result == "0" ]; then
                editConnections;
        fi

        finalUser="";
        finalConnection="";

        i=1;
        for user in $SSHLS_USER; do
                if [ $i == $result ]; then
                        finalUser=$user;
                fi
                i=$(( $i+1 ));
        done
        i=1
        for connection in $SSHLS_CONNECTIONS; do
                if [ $i == $result ]; then
                        finalConnection=$connection;
                fi
                i=$(( $i+1 ));
        done

        ssh $finalUser@$finalConnection;

}
editConnections() {
        exec 3>&1;
        result=$(dialog --menu "Add or Remove Connection" 15 50 7 "0" "Add" "1" "Remove" 2>&1 1>&3);
        exitcode=$?;
        exec 3>&-;
        echo $result $exitcode;

        echo $result;
        if [ $result == "0" ]; then
                addConnection;
        elif [$result == "1" ]; then
                removeConnection;
        else
                echo $result;
        fi
        selectConnection;
}

addConnection() {
        echo "Enter Host Address:"
        read sshaddress
        echo "Enter Host Name:"
        read sshname
        echo "Enter User Name:"
        read username

        echo "$sshname:$sshaddress:$username" >> $SSHLS_PATH
}

removeConnection() {
        result=$(dialog --menu "Select Host to Delete" 15 70 7 $SSHLS_OPTIONS 2>&1 1>&3);
        exitcode=$?;
        exec 3>&-;
        echo "RESULT" $result "EXITCODE" $exitcode;

        if [ $exitcode != "0" ]; then
                selectConnection;
        fi


        if [ $result == "0" ]; then
                editConnections;
        fi



        echo "Cancel";
}


main "$@"
